// Placeholder — will be generated by `supabase gen types typescript`
// For now, define minimal types to unblock development

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          user_id: string;
          display_name: string | null;
          avatar_url: string | null;
          timezone: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          display_name?: string | null;
          avatar_url?: string | null;
          timezone?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          display_name?: string | null;
          avatar_url?: string | null;
          timezone?: string;
        };
      };
      categories: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          color: string;
          icon: string;
          sort_order: number;
          is_archived: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          color?: string;
          icon?: string;
          sort_order?: number;
          is_archived?: boolean;
        };
        Update: {
          name?: string;
          color?: string;
          icon?: string;
          sort_order?: number;
          is_archived?: boolean;
        };
      };
      time_entries: {
        Row: {
          id: string;
          user_id: string;
          category_id: string;
          started_at: string;
          ended_at: string | null;
          duration_seconds: number | null;
          entry_type: "timer" | "manual" | "pomodoro";
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          category_id: string;
          started_at: string;
          ended_at?: string | null;
          duration_seconds?: number | null;
          entry_type?: "timer" | "manual" | "pomodoro";
          notes?: string | null;
        };
        Update: {
          category_id?: string;
          ended_at?: string | null;
          duration_seconds?: number | null;
          notes?: string | null;
        };
      };
      pomodoro_sessions: {
        Row: {
          id: string;
          user_id: string;
          time_entry_id: string | null;
          work_minutes: number;
          break_minutes: number;
          completed_cycles: number;
          total_cycles: number;
          status: "active" | "completed" | "cancelled";
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          time_entry_id?: string | null;
          work_minutes?: number;
          break_minutes?: number;
          completed_cycles?: number;
          total_cycles?: number;
          status?: "active" | "completed" | "cancelled";
        };
        Update: {
          time_entry_id?: string | null;
          completed_cycles?: number;
          status?: "active" | "completed" | "cancelled";
        };
      };
      streaks: {
        Row: {
          id: string;
          user_id: string;
          current_streak: number;
          longest_streak: number;
          last_active_date: string | null;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          current_streak?: number;
          longest_streak?: number;
          last_active_date?: string | null;
        };
        Update: {
          current_streak?: number;
          longest_streak?: number;
          last_active_date?: string | null;
        };
      };
      goals: {
        Row: {
          id: string;
          user_id: string;
          category_id: string | null;
          target_minutes: number;
          period: "daily" | "weekly" | "monthly";
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          category_id?: string | null;
          target_minutes: number;
          period?: "daily" | "weekly" | "monthly";
          is_active?: boolean;
        };
        Update: {
          category_id?: string | null;
          target_minutes?: number;
          period?: "daily" | "weekly" | "monthly";
          is_active?: boolean;
        };
      };
      user_badges: {
        Row: {
          id: string;
          user_id: string;
          badge_key: string;
          badge_definition_key: string | null;
          earned_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          badge_key?: string;
          badge_definition_key?: string;
        };
        Update: Record<string, never>;
      };
      challenges: {
        Row: {
          id: string;
          user_id: string;
          challenge_key: string;
          target_minutes: number;
          progress_minutes: number;
          period_start: string;
          period_end: string;
          status: "active" | "completed" | "expired";
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          challenge_key: string;
          target_minutes: number;
          progress_minutes?: number;
          period_start: string;
          period_end: string;
          status?: "active" | "completed" | "expired";
        };
        Update: {
          progress_minutes?: number;
          status?: "active" | "completed" | "expired";
        };
      };
      user_preferences: {
        Row: {
          id: string;
          user_id: string;
          theme: "light" | "dark" | "system";
          preferred_background: string;
          preferred_ambient_sound: string;
          pomodoro_preset: "25/5" | "50/10" | "90/20" | "custom";
          custom_work_minutes: number;
          custom_break_minutes: number;
          email_digest_enabled: boolean;
          last_digest_sent_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          theme?: "light" | "dark" | "system";
          preferred_background?: string;
          preferred_ambient_sound?: string;
          pomodoro_preset?: "25/5" | "50/10" | "90/20" | "custom";
          custom_work_minutes?: number;
          custom_break_minutes?: number;
          email_digest_enabled?: boolean;
        };
        Update: {
          theme?: "light" | "dark" | "system";
          preferred_background?: string;
          preferred_ambient_sound?: string;
          pomodoro_preset?: "25/5" | "50/10" | "90/20" | "custom";
          custom_work_minutes?: number;
          custom_break_minutes?: number;
          email_digest_enabled?: boolean;
        };
      };
      user_stats: {
        Row: {
          user_id: string;
          total_xp: number;
          current_level: number;
          total_focus_minutes: number;
          weekly_focus_minutes: number;
          monthly_focus_minutes: number;
          current_streak: number;
          longest_streak: number;
          last_active_date: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          total_xp?: number;
          current_level?: number;
          total_focus_minutes?: number;
          weekly_focus_minutes?: number;
          monthly_focus_minutes?: number;
          current_streak?: number;
          longest_streak?: number;
          last_active_date?: string | null;
        };
        Update: {
          total_xp?: number;
          current_level?: number;
          total_focus_minutes?: number;
          weekly_focus_minutes?: number;
          monthly_focus_minutes?: number;
          current_streak?: number;
          longest_streak?: number;
          last_active_date?: string | null;
        };
      };
      crystal_customizations: {
        Row: {
          user_id: string;
          unlocked_shapes: string[];
          unlocked_colors: string[];
          unlocked_themes: string[];
          active_shape: string;
          active_color: string;
          active_theme: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          unlocked_shapes?: string[];
          unlocked_colors?: string[];
          unlocked_themes?: string[];
          active_shape?: string;
          active_color?: string;
          active_theme?: string;
        };
        Update: {
          unlocked_shapes?: string[];
          unlocked_colors?: string[];
          unlocked_themes?: string[];
          active_shape?: string;
          active_color?: string;
          active_theme?: string;
        };
      };
      badge_definitions: {
        Row: {
          key: string;
          name: string;
          description: string;
          icon: string;
          rarity: "common" | "rare" | "epic" | "legendary";
          condition_type: string;
          condition_value: number;
          xp_reward: number;
          created_at: string;
        };
        Insert: {
          key: string;
          name: string;
          description: string;
          icon: string;
          rarity?: "common" | "rare" | "epic" | "legendary";
          condition_type: string;
          condition_value?: number;
          xp_reward?: number;
        };
        Update: Record<string, never>;
      };
      weekly_challenges: {
        Row: {
          id: string;
          challenge_key: string;
          name: string;
          description: string;
          challenge_type: string;
          target_value: number;
          xp_reward: number;
          week_start: string;
          week_end: string;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          challenge_key: string;
          name: string;
          description: string;
          challenge_type: string;
          target_value: number;
          xp_reward?: number;
          week_start: string;
          week_end: string;
          is_active?: boolean;
        };
        Update: {
          is_active?: boolean;
        };
      };
      weekly_challenge_progress: {
        Row: {
          id: string;
          user_id: string;
          challenge_id: string;
          progress_current: number;
          progress_target: number;
          status: "active" | "completed" | "expired";
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          challenge_id: string;
          progress_current?: number;
          progress_target: number;
          status?: "active" | "completed" | "expired";
          completed_at?: string | null;
        };
        Update: {
          progress_current?: number;
          status?: "active" | "completed" | "expired";
          completed_at?: string | null;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      entry_type: "timer" | "manual" | "pomodoro";
      pomodoro_status: "active" | "completed" | "cancelled";
      goal_period: "daily" | "weekly" | "monthly";
      theme_mode: "light" | "dark" | "system";
      pomodoro_preset: "25/5" | "50/10" | "90/20" | "custom";
      challenge_status: "active" | "completed" | "expired";
      badge_rarity: "common" | "rare" | "epic" | "legendary";
      crystal_shape: "icosahedron" | "dodecahedron" | "octahedron" | "tetrahedron" | "torus_knot";
      crystal_color: "blue" | "purple" | "emerald" | "amber" | "rose" | "cyan" | "gold" | "obsidian";
      crystal_theme: "default" | "ethereal" | "fiery" | "ocean" | "cosmic" | "forest";
    };
  };
};
