// Placeholder — will be generated by `supabase gen types typescript`
// For now, define minimal types to unblock development

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          user_id: string;
          display_name: string | null;
          avatar_url: string | null;
          timezone: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          display_name?: string | null;
          avatar_url?: string | null;
          timezone?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          display_name?: string | null;
          avatar_url?: string | null;
          timezone?: string;
        };
      };
      categories: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          color: string;
          icon: string;
          sort_order: number;
          is_archived: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          color?: string;
          icon?: string;
          sort_order?: number;
          is_archived?: boolean;
        };
        Update: {
          name?: string;
          color?: string;
          icon?: string;
          sort_order?: number;
          is_archived?: boolean;
        };
      };
      time_entries: {
        Row: {
          id: string;
          user_id: string;
          category_id: string;
          started_at: string;
          ended_at: string | null;
          duration_seconds: number | null;
          entry_type: "timer" | "manual" | "pomodoro";
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          category_id: string;
          started_at: string;
          ended_at?: string | null;
          duration_seconds?: number | null;
          entry_type?: "timer" | "manual" | "pomodoro";
          notes?: string | null;
        };
        Update: {
          category_id?: string;
          ended_at?: string | null;
          duration_seconds?: number | null;
          notes?: string | null;
        };
      };
      pomodoro_sessions: {
        Row: {
          id: string;
          user_id: string;
          time_entry_id: string | null;
          work_minutes: number;
          break_minutes: number;
          completed_cycles: number;
          total_cycles: number;
          status: "active" | "completed" | "cancelled";
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          time_entry_id?: string | null;
          work_minutes?: number;
          break_minutes?: number;
          completed_cycles?: number;
          total_cycles?: number;
          status?: "active" | "completed" | "cancelled";
        };
        Update: {
          time_entry_id?: string | null;
          completed_cycles?: number;
          status?: "active" | "completed" | "cancelled";
        };
      };
      streaks: {
        Row: {
          id: string;
          user_id: string;
          current_streak: number;
          longest_streak: number;
          last_active_date: string | null;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          current_streak?: number;
          longest_streak?: number;
          last_active_date?: string | null;
        };
        Update: {
          current_streak?: number;
          longest_streak?: number;
          last_active_date?: string | null;
        };
      };
      goals: {
        Row: {
          id: string;
          user_id: string;
          category_id: string | null;
          target_minutes: number;
          period: "daily" | "weekly" | "monthly";
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          category_id?: string | null;
          target_minutes: number;
          period?: "daily" | "weekly" | "monthly";
          is_active?: boolean;
        };
        Update: {
          category_id?: string | null;
          target_minutes?: number;
          period?: "daily" | "weekly" | "monthly";
          is_active?: boolean;
        };
      };
      user_badges: {
        Row: {
          id: string;
          user_id: string;
          badge_key: string;
          earned_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          badge_key: string;
        };
        Update: Record<string, never>;
      };
      challenges: {
        Row: {
          id: string;
          user_id: string;
          challenge_key: string;
          target_minutes: number;
          progress_minutes: number;
          period_start: string;
          period_end: string;
          status: "active" | "completed" | "expired";
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          challenge_key: string;
          target_minutes: number;
          progress_minutes?: number;
          period_start: string;
          period_end: string;
          status?: "active" | "completed" | "expired";
        };
        Update: {
          progress_minutes?: number;
          status?: "active" | "completed" | "expired";
        };
      };
      user_preferences: {
        Row: {
          id: string;
          user_id: string;
          theme: "light" | "dark" | "system";
          preferred_background: string;
          preferred_ambient_sound: string;
          pomodoro_preset: "25/5" | "50/10" | "90/20" | "custom";
          custom_work_minutes: number;
          custom_break_minutes: number;
          email_digest_enabled: boolean;
          last_digest_sent_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          theme?: "light" | "dark" | "system";
          preferred_background?: string;
          preferred_ambient_sound?: string;
          pomodoro_preset?: "25/5" | "50/10" | "90/20" | "custom";
          custom_work_minutes?: number;
          custom_break_minutes?: number;
          email_digest_enabled?: boolean;
        };
        Update: {
          theme?: "light" | "dark" | "system";
          preferred_background?: string;
          preferred_ambient_sound?: string;
          pomodoro_preset?: "25/5" | "50/10" | "90/20" | "custom";
          custom_work_minutes?: number;
          custom_break_minutes?: number;
          email_digest_enabled?: boolean;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      entry_type: "timer" | "manual" | "pomodoro";
      pomodoro_status: "active" | "completed" | "cancelled";
      goal_period: "daily" | "weekly" | "monthly";
      theme_mode: "light" | "dark" | "system";
      pomodoro_preset: "25/5" | "50/10" | "90/20" | "custom";
      challenge_status: "active" | "completed" | "expired";
    };
  };
};
