"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { cn } from "@/lib/utils";
import {
  Briefcase,
  BookOpen,
  Dumbbell,
  User,
  Code,
  Coffee,
  Music,
  Video,
  Gamepad2,
  ShoppingBag,
  Home,
  Car,
  Plane,
  Heart,
  Star,
  Sun,
  Moon,
  Cloud,
  Zap,
  Flame,
  Target,
  Trophy,
  Medal,
  Award,
  Lightbulb,
  PenTool,
  Brush,
  Camera,
  Mic,
  Headphones,
  Speaker,
  Tv,
  Smartphone,
  Laptop,
  Monitor,
  Keyboard,
  Mouse,
  Wifi,
  Battery,
  Plug,
  Key,
  Lock,
  Unlock,
  Shield,
  AlertTriangle,
  CheckCircle,
  XCircle,
  HelpCircle,
  Info,
  Search,
  Filter,
  Settings,
  Sliders,
  Menu,
  Grid,
  List,
  Layout,
  Maximize,
  Minimize,
  Plus,
  Minus,
  X,
  Check,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  ChevronDown,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Link,
  Paperclip,
  FileText,
  File,
  Folder,
  FolderOpen,
  Image,
  ImageIcon,
  MapPin,
  Navigation,
  Compass,
  Globe,
  Flag,
  Bookmark,
  Tag,
  Hash,
  AtSign,
  Mail,
  MessageSquare,
  MessageCircle,
  Phone,
  PhoneCall,
  Video,
  VideoIcon,
  Calendar,
  Clock,
  Timer,
  Hourglass,
  Bell,
  BellRing,
  Volume2,
  VolumeX,
  Mic2,
  MicOff,
  Eye,
  EyeOff,
  ThumbsUp,
  ThumbsDown,
  HeartIcon,
  Share2,
  Upload,
  Download,
  Save,
  Printer,
  Copy,
  Scissors,
  Trash2,
  Archive,
  Edit3,
  Edit2,
  PenLine,
  Type,
  AlignLeft,
  AlignCenter,
  AlignRight,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  Code2,
  Terminal,
  Database,
  Server,
  HardDrive,
  Cpu,
  Layers,
  Box,
  Package,
  Gift,
  CreditCard,
  DollarSign,
  Wallet,
  Receipt,
  ShoppingCart,
  Truck,
  Anchor,
  CompassIcon,
  Map,
  Mountain,
  TreePine,
  Flower,
  Leaf,
  Apple,
  CoffeeIcon,
  Utensils,
  Pizza,
  IceCream,
  Cookie,
  Beer,
  Wine,
  GlassWater,
  Droplet,
  Thermometer,
  Wind,
  CloudRain,
  CloudSnow,
  CloudLightning,
  Umbrella,
  Snowflake,
  Waves,
  FlameIcon,
  Bomb,
  Skull,
  Ghost,
  Sparkles,
  Rainbow,
  Puzzle,
  ToyBrick,
  Dice,
  TrophyIcon,
  Crown,
  Gem,
  Diamond,
  Coins,
  Banknote,
  PiggyBank,
  Calculator,
  ChartBar,
  ChartLine,
  ChartPie,
  TrendingUp,
  TrendingDown,
  Activity,
  HeartPulse,
  Stethoscope,
  Pill,
  Syringe,
  Bandage,
  ScissorsIcon,
  Microscope,
  Telescope,
  Rocket,
  Satellite,
  Alien,
  Robot,
  Brain,
  PuzzleIcon,
  GraduationCap,
  School,
  Library,
  BookMarked,
  Newspaper,
  Rss,
  Radio,
  Podcast,
  Megaphone,
  Bullhorn,
  Ticket,
  Clapperboard,
  Film,
  Popcorn,
  Palette,
  Paintbrush,
  PaintBucket,
  Eraser,
  Ruler,
  Pencil,
  Highlighter,
  Sticker,
  StickyNote,
  Clipboard,
  ClipboardList,
  ClipboardCheck,
  FileCheck,
  FilePlus,
  FileMinus,
  FileX,
  FileQuestion,
  FileWarning,
  FileCode,
  FileJson,
  FileType,
  FileImage,
  FileVideo,
  FileAudio,
  FileArchive,
  FileSpreadsheet,
  FilePieChart,
  FolderPlus,
  FolderMinus,
  FolderTree,
  FolderKanban,
  Folders,
  BriefcaseIcon,
  Building,
  Building2,
  Store,
  Warehouse,
  Factory,
  Landmark,
  Castle,
  Church,
  Mosque,
  Synagogue,
  Tent,
  TreeDeciduous,
  TreeIcon,
  Flower2,
  Sprout,
  Seedling,
  Recycle,
  TrashIcon,
  Shovel,
  Hammer,
  Wrench,
  Screwdriver,
  Drill,
  Saw,
  Axe,
  Pickaxe,
  Sword,
  ShieldIcon,
  ShieldAlert,
  ShieldCheck,
  ShieldQuestion,
  ShieldX,
  Badge,
  BadgeCheck,
  BadgeAlert,
  BadgeX,
  Fingerprint,
  Scan,
  ScanFace,
  ScanLine,
  ScanSearch,
  QrCode,
  Barcode,
  Nfc,
  RssIcon,
  WifiIcon,
  WifiOff,
  Bluetooth,
  Usb,
  HDMI,
  Cast,
  Airplay,
  ScreenShare,
  MonitorPlay,
  MonitorStop,
  SmartphoneIcon,
  Tablet,
  Watch,
  Glasses,
  Sunglasses,
  Hat,
  Shirt,
  ShoppingBagIcon,
  ShoppingBasket,
  TagIcon,
  Tags,
  Label,
  StickerIcon,
  Stamp,
  Inbox,
  MailIcon,
  MailOpen,
  MailPlus,
  MailMinus,
  MailCheck,
  MailX,
  MailQuestion,
  MailWarning,
  Send,
  SendHorizonal,
  Reply,
  ReplyAll,
  Forward,
  ShareIcon,
  LinkIcon,
  Link2,
  Unlink,
  Unlink2,
  PaperclipIcon,
  Attachment,
  ImagePlus,
  ImageMinus,
  ImageDown,
  Images,
  GalleryHorizontal,
  GalleryVertical,
  LayoutGrid,
  LayoutList,
  LayoutTemplate,
  LayoutDashboard,
  PanelsTopLeft,
  Sidebar,
  PanelLeft,
  PanelRight,
  PanelTop,
  PanelBottom,
  Split,
  Columns,
  Rows,
  Grid3X3,
  Grid2X2,
  Table,
  ListIcon,
  ListOrdered,
  ListChecks,
  ListTodo,
  ListStart,
  ListEnd,
  ListVideo,
  ListMusic,
  ListCollapse,
  Kanban,
  KanbanSquare,
  GanttChart,
  BarChart,
  BarChart2,
  BarChart3,
  BarChart4,
  LineChart,
  AreaChart,
  PieChart,
  Radar,
  TargetIcon,
  Crosshair,
  Focus,
  FocusIcon,
  Aperture,
  ScanEye,
  EyeIcon,
  GlassesIcon,
  Contact,
  Contact2,
  UserIcon,
  UserPlus,
  UserMinus,
  UserX,
  UserCheck,
  Users,
  UsersPlus,
  UsersMinus,
  UsersX,
  UsersRound,
  UserCircle,
  UserCog,
  UserCog2,
  UserRound,
  Baby,
  Accessibility,
  AccessibilityIcon,
  Armchair,
  Bath,
  Bed,
  BedDouble,
  BedSingle,
  Sofa,
  Lamp,
  LampDesk,
  LampFloor,
  LampWall,
  LightbulbIcon,
  Flashlight,
  CandlestickChart,
  FlameKindling,
  FireExtinguisher,
  Hydrant,
  Siren,
  AlertOctagon,
  AlertCircle,
  AlertTriangleIcon,
  MegaphoneIcon,
  BellIcon,
  BellPlus,
  BellMinus,
  BellOff,
  BellRingIcon,
  BellDot,
  PackageIcon,
  Package2,
  PackageCheck,
  PackageX,
  PackageSearch,
  PackageOpen,
  Container,
  ShippingContainer,
  TruckIcon,
  PlaneIcon,
  PlaneTakeoff,
  PlaneLanding,
  Train,
  TrainFront,
  Bus,
  CarIcon,
  CarFront,
  CarTaxiFront,
  Bike,
  Footprints,
  MapPinned,
  MapIcon,
  Globe2,
  GlobeIcon,
  Earth,
  Languages,
  BookIcon,
  BookCopy,
  BookDown,
  BookKey,
  BookLock,
  BookUp,
  BookX,
  BookmarkIcon,
  BookmarkPlus,
  BookmarkMinus,
  BookmarkX,
  BookmarkCheck,
  LibraryIcon,
  GraduationCapIcon,
  AwardIcon,
  MedalIcon,
  TrophyIcon,
  CrownIcon,
} from "lucide-react";

// Common emojis for categories
const EMOJI_ICONS = [
  "💼", "📚", "💪", "👤", "💻", "☕", "🎵", "🎬", "🎮", "🛍️",
  "🏠", "🚗", "✈️", "❤️", "⭐", "☀️", "🌙", "☁️", "⚡", "🔥",
  "🎯", "🏆", "🥇", "🏅", "💡", "✏️", "🎨", "📷", "🎤", "🎧",
  "📺", "📱", "💻", "🖥️", "⌨️", "🖱️", "📶", "🔋", "🔌", "🔑",
  "🔒", "🔓", "🛡️", "⚠️", "✅", "❌", "❓", "ℹ️", "🔍", "🔎",
  "⚙️", "🎚️", "☰", "⊞", "☰", "⧉", "⤢", "⤡", "➕", "➖",
  "✕", "✓", "›", "‹", "⌃", "⌄", "→", "←", "↑", "↓",
  "↗", "🔗", "📎", "📄", "📁", "📂", "📂", "🖼️", "🗺️", "🧭",
  "🌍", "🚩", "🔖", "🏷️", "#️⃣", "@", "✉️", "💬", "💭", "📞",
  "📹", "🎥", "📅", "🕐", "⏱️", "⏳", "🔔", "🔕", "🔊", "🔇",
  "👁️", "🙈", "👍", "👎", "💓", "📤", "📥", "💾", "🖨️", "📋",
  "✂️", "🗑️", "📝", "🖊️", "🖋️", "T", "⬅", "·", "B", "I",
  "U", "S", "</>", "⌨", "🗄️", "🖥", "💾", "🧠", "📦", "🎁",
  "💳", "💵", "👛", "🧾", "🛒", "🚚", "⚓", "🧭", "🗺", "⛰️",
  "🌲", "🌸", "🍃", "🍎", "☕", "🍽️", "🍕", "🍦", "🍪", "🍺",
  "🍷", "🥛", "💧", "🌡️", "💨", "🌧️", "❄️", "⚡", "☂️", "❄️",
  "🌊", "🔥", "💣", "💀", "👻", "✨", "🌈", "🧩", "🧱", "🎲",
  "🏆", "👑", "💎", "💠", "🪙", "💰", "🐷", "🧮", "📊", "📈",
  "📉", "📉", "💓", "🩺", "💊", "💉", "🩹", "✂️", "🔬", "🔭",
  "🚀", "🛰️", "👽", "🤖", "🧠", "🧩", "🎓", "🏫", "📚", "🔖",
  "📰", "📡", "📻", "🎙️", "📣", "🎫", "🎬", "🎞️", "🍿", "🎨",
  "🖌️", "🎨", "🧽", "📏", "✏️", "🖍️", "📝", "🗒️", "📋", "✅",
  "➕", "➖", "✕", "❓", "⚠️", "</>", "{}", "T", "🖼️", "🎬",
  "🔊", "🗜️", "📊", "📁", "➕", "➖", "🌳", "📁", "📂", "📂",
  "💼", "🏢", "🏬", "🏭", "🏛️", "🏰", "⛪", "🕌", "🕍", "⛺",
  "🌳", "🌲", "🌸", "🌱", "♻️", "🗑️", "⛏️", "🔨", "🔧", "🪛",
  "🔩", "🪚", "🪓", "⛏️", "⚔️", "🛡️", "🛡️", "✅", "❓", "❌",
  "🏷️", "✅", "⚠️", "❌", "👆", "🔍", "👤", "🔍", "🏁", "🌐",
  "📡", "📶", "📴", "🔵", "🔌", "📺", "🖥️", "📺", "⏹️", "📱",
  "📲", "⌚", "👓", "🕶️", "🎩", "👕", "🛍️", "🧺", "🏷️", "🏷️",
  "🏷️", "📮", "📨", "📩", "📨", "➕", "➖", "✅", "❌", "❓",
  "⚠️", "📤", "➡️", "↩️", "↪️", "➡️", "🔗", "🔗", "🔗", "🔗",
  "📎", "📎", "🖼️", "➕", "➖", "⬇️", "🖼️", "🖼️", "⬅➡", "⬆⬇",
  "⊞", "☰", "⧈", "⧉", "⬅", "➡", "⬆", "⬇", "⊟", "⧇",
  "▦", "☰", "🔢", "☑", "☰", "▶", "🎵", "⤵", "📋", "📋",
  "📊", "📈", "📉", "🎯", "🎯", "🎯", "📷", "👁", "👓", "📝",
  "👤", "➕", "➖", "❌", "✓", "👥", "➕", "➖", "❌", "👥",
  "👤", "⚙", "👤", "👶", "♿", "♿", "🪑", "🛁", "🛏️", "🛏️",
  "🛋️", "💡", "💡", "🕯️", "📊", "🔥", "🧯", "🚨", "🚨", "⭕",
  "🔔", "🔔", "➕", "➖", "📴", "🔔", "🔔", "📦", "📦", "📦",
  "✅", "❌", "🔍", "📦", "📦", "🚢", "🚛", "✈️", "🛫", "🛬",
  "🚂", "🚆", "🚌", "🚗", "🚘", "🚕", "🚲", "👣", "📍", "🗺️",
  "🌍", "🌎", "🌏", "🌐", "🗣️", "📖", "📚", "📚", "📖", "📖",
  "🔑", "🔒", "🔓", "📖", "❌", "🔖", "🔖", "➕", "➖", "❌",
  "✓", "📚", "🎓", "🏆", "🥇", "🏆", "👑",
];

// Map of icon names to Lucide components
const LUCIDE_ICONS: Record<string, React.ComponentType<{ className?: string }>> = {
  briefcase: Briefcase,
  book: BookOpen,
  dumbbell: Dumbbell,
  user: User,
  code: Code,
  coffee: Coffee,
  music: Music,
  video: Video,
  gamepad: Gamepad2,
  shopping: ShoppingBag,
  home: Home,
  car: Car,
  plane: Plane,
  heart: Heart,
  star: Star,
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  zap: Zap,
  flame: Flame,
  target: Target,
  trophy: Trophy,
  medal: Medal,
  award: Award,
  lightbulb: Lightbulb,
  pen: PenTool,
  brush: Brush,
  camera: Camera,
  mic: Mic,
  headphones: Headphones,
  speaker: Speaker,
  tv: Tv,
  smartphone: Smartphone,
  laptop: Laptop,
  monitor: Monitor,
  keyboard: Keyboard,
  mouse: Mouse,
  wifi: Wifi,
  battery: Battery,
  plug: Plug,
  key: Key,
  lock: Lock,
  unlock: Unlock,
  shield: Shield,
  alert: AlertTriangle,
  check: CheckCircle,
  x: XCircle,
  help: HelpCircle,
  info: Info,
  search: Search,
  filter: Filter,
  settings: Settings,
  sliders: Sliders,
  menu: Menu,
  grid: Grid,
  list: List,
  layout: Layout,
  maximize: Maximize,
  minimize: Minimize,
  plus: Plus,
  minus: Minus,
  xmark: X,
  checkmark: Check,
  "chevron-right": ChevronRight,
  "chevron-left": ChevronLeft,
  "chevron-up": ChevronUp,
  "chevron-down": ChevronDown,
  "arrow-right": ArrowRight,
  "arrow-left": ArrowLeft,
  "arrow-up": ArrowUp,
  "arrow-down": ArrowDown,
  "external-link": ExternalLink,
  link: Link,
  paperclip: Paperclip,
  "file-text": FileText,
  file: File,
  folder: Folder,
  "folder-open": FolderOpen,
  image: Image,
  "image-icon": ImageIcon,
  "map-pin": MapPin,
  navigation: Navigation,
  compass: Compass,
  globe: Globe,
  flag: Flag,
  bookmark: Bookmark,
  tag: Tag,
  hash: Hash,
  at: AtSign,
  mail: Mail,
  "message-square": MessageSquare,
  "message-circle": MessageCircle,
  phone: Phone,
  "phone-call": PhoneCall,
  calendar: Calendar,
  clock: Clock,
  timer: Timer,
  hourglass: Hourglass,
  bell: Bell,
  "bell-ring": BellRing,
  volume: Volume2,
  mute: VolumeX,
  mic2: Mic2,
  "mic-off": MicOff,
  eye: Eye,
  "eye-off": EyeOff,
  "thumbs-up": ThumbsUp,
  "thumbs-down": ThumbsDown,
  "heart-icon": HeartIcon,
  share: Share2,
  upload: Upload,
  download: Download,
  save: Save,
  print: Printer,
  copy: Copy,
  scissors: Scissors,
  trash: Trash2,
  archive: Archive,
  edit3: Edit3,
  edit2: Edit2,
  "pen-line": PenLine,
  type: Type,
  "align-left": AlignLeft,
  "align-center": AlignCenter,
  "align-right": AlignRight,
  bold: Bold,
  italic: Italic,
  underline: Underline,
  strikethrough: Strikethrough,
  "code-2": Code2,
  terminal: Terminal,
  database: Database,
  server: Server,
  "hard-drive": HardDrive,
  cpu: Cpu,
  layers: Layers,
  box: Box,
  package: Package,
  gift: Gift,
  "credit-card": CreditCard,
  "dollar-sign": DollarSign,
  wallet: Wallet,
  receipt: Receipt,
  "shopping-cart": ShoppingCart,
  truck: Truck,
  anchor: Anchor,
  map: Map,
  mountain: Mountain,
  "tree-pine": TreePine,
  flower: Flower,
  leaf: Leaf,
  apple: Apple,
  utensils: Utensils,
  pizza: Pizza,
  "ice-cream": IceCream,
  cookie: Cookie,
  beer: Beer,
  wine: Wine,
  "glass-water": GlassWater,
  droplet: Droplet,
  thermometer: Thermometer,
  wind: Wind,
  "cloud-rain": CloudRain,
  "cloud-snow": CloudSnow,
  "cloud-lightning": CloudLightning,
  umbrella: Umbrella,
  snowflake: Snowflake,
  waves: Waves,
  "flame-icon": FlameIcon,
  bomb: Bomb,
  skull: Skull,
  ghost: Ghost,
  sparkles: Sparkles,
  rainbow: Rainbow,
  puzzle: Puzzle,
  "toy-brick": ToyBrick,
  dice: Dice,
  "trophy-icon": TrophyIcon,
  crown: Crown,
  gem: Gem,
  diamond: Diamond,
  coins: Coins,
  banknote: Banknote,
  "piggy-bank": PiggyBank,
  calculator: Calculator,
  "chart-bar": ChartBar,
  "chart-line": ChartLine,
  "chart-pie": ChartPie,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  activity: Activity,
  "heart-pulse": HeartPulse,
  stethoscope: Stethoscope,
  pill: Pill,
  syringe: Syringe,
  bandage: Bandage,
  microscope: Microscope,
  telescope: Telescope,
  rocket: Rocket,
  satellite: Satellite,
  alien: Alien,
  robot: Robot,
  brain: Brain,
  graduation: GraduationCap,
  school: School,
  library: Library,
  "book-marked": BookMarked,
  newspaper: Newspaper,
  rss: Rss,
  radio: Radio,
  podcast: Podcast,
  megaphone: Megaphone,
  bullhorn: Bullhorn,
  ticket: Ticket,
  clapperboard: Clapperboard,
  film: Film,
  popcorn: Popcorn,
  palette: Palette,
  paintbrush: Paintbrush,
  "paint-bucket": PaintBucket,
  eraser: Eraser,
  ruler: Ruler,
  pencil: Pencil,
  highlighter: Highlighter,
  sticker: Sticker,
  "sticky-note": StickyNote,
  clipboard: Clipboard,
  "clipboard-list": ClipboardList,
  "clipboard-check": ClipboardCheck,
  "file-check": FileCheck,
  "file-plus": FilePlus,
  "file-minus": FileMinus,
  "file-x": FileX,
  "file-question": FileQuestion,
  "file-warning": FileWarning,
  "file-code": FileCode,
  "file-json": FileJson,
  "file-type": FileType,
  "file-image": FileImage,
  "file-video": FileVideo,
  "file-audio": FileAudio,
  "file-archive": FileArchive,
  "file-spreadsheet": FileSpreadsheet,
  "file-pie-chart": FilePieChart,
  "folder-plus": FolderPlus,
  "folder-minus": FolderMinus,
  "folder-tree": FolderTree,
  "folder-kanban": FolderKanban,
  folders: Folders,
  "briefcase-icon": BriefcaseIcon,
  building: Building,
  building2: Building2,
  store: Store,
  warehouse: Warehouse,
  factory: Factory,
  landmark: Landmark,
  castle: Castle,
  church: Church,
  mosque: Mosque,
  synagogue: Synagogue,
  tent: Tent,
  "tree-deciduous": TreeDeciduous,
  "tree-icon": TreeIcon,
  flower2: Flower2,
  sprout: Sprout,
  seedling: Seedling,
  recycle: Recycle,
  "trash-icon": TrashIcon,
  shovel: Shovel,
  hammer: Hammer,
  wrench: Wrench,
  screwdriver: Screwdriver,
  drill: Drill,
  saw: Saw,
  axe: Axe,
  pickaxe: Pickaxe,
  sword: Sword,
  "shield-icon": ShieldIcon,
  "shield-alert": ShieldAlert,
  "shield-check": ShieldCheck,
  "shield-question": ShieldQuestion,
  "shield-x": ShieldX,
  badge: Badge,
  "badge-check": BadgeCheck,
  "badge-alert": BadgeAlert,
  "badge-x": BadgeX,
  fingerprint: Fingerprint,
  scan: Scan,
  "scan-face": ScanFace,
  "scan-line": ScanLine,
  "scan-search": ScanSearch,
  "qr-code": QrCode,
  barcode: Barcode,
  nfc: Nfc,
  "rss-icon": RssIcon,
  "wifi-icon": WifiIcon,
  "wifi-off": WifiOff,
  bluetooth: Bluetooth,
  usb: Usb,
  hdmi: HDMI,
  cast: Cast,
  airplay: Airplay,
  "screen-share": ScreenShare,
  "monitor-play": MonitorPlay,
  "monitor-stop": MonitorStop,
  "smartphone-icon": SmartphoneIcon,
  tablet: Tablet,
  watch: Watch,
  glasses: Glasses,
  sunglasses: Sunglasses,
  hat: Hat,
  shirt: Shirt,
  "shopping-bag-icon": ShoppingBagIcon,
  "shopping-basket": ShoppingBasket,
  "tag-icon": TagIcon,
  tags: Tags,
  label: Label,
  "sticker-icon": StickerIcon,
  stamp: Stamp,
  inbox: Inbox,
  "mail-icon": MailIcon,
  "mail-open": MailOpen,
  "mail-plus": MailPlus,
  "mail-minus": MailMinus,
  "mail-check": MailCheck,
  "mail-x": MailX,
  "mail-question": MailQuestion,
  "mail-warning": MailWarning,
  send: Send,
  "send-horizontal": SendHorizonal,
  reply: Reply,
  "reply-all": ReplyAll,
  forward: Forward,
  "share-icon": ShareIcon,
  "link-icon": LinkIcon,
  "link-2": Link2,
  unlink: Unlink,
  "unlink-2": Unlink2,
  "paperclip-icon": PaperclipIcon,
  attachment: Attachment,
  "image-plus": ImagePlus,
  "image-minus": ImageMinus,
  "image-down": ImageDown,
  images: Images,
  "gallery-horizontal": GalleryHorizontal,
  "gallery-vertical": GalleryVertical,
  "layout-grid": LayoutGrid,
  "layout-list": LayoutList,
  "layout-template": LayoutTemplate,
  "layout-dashboard": LayoutDashboard,
  "panels-top-left": PanelsTopLeft,
  sidebar: Sidebar,
  "panel-left": PanelLeft,
  "panel-right": PanelRight,
  "panel-top": PanelTop,
  "panel-bottom": PanelBottom,
  split: Split,
  columns: Columns,
  rows: Rows,
  "grid-3x3": Grid3X3,
  "grid-2x2": Grid2X2,
  table: Table,
  "list-icon": ListIcon,
  "list-ordered": ListOrdered,
  "list-checks": ListChecks,
  "list-todo": ListTodo,
  "list-start": ListStart,
  "list-end": ListEnd,
  "list-video": ListVideo,
  "list-music": ListMusic,
  "list-collapse": ListCollapse,
  kanban: Kanban,
  "kanban-square": KanbanSquare,
  "gantt-chart": GanttChart,
  "bar-chart": BarChart,
  "bar-chart-2": BarChart2,
  "bar-chart-3": BarChart3,
  "bar-chart-4": BarChart4,
  "line-chart": LineChart,
  "area-chart": AreaChart,
  "pie-chart": PieChart,
  radar: Radar,
  "target-icon": TargetIcon,
  crosshair: Crosshair,
  focus: Focus,
  "focus-icon": FocusIcon,
  aperture: Aperture,
  "scan-eye": ScanEye,
  "eye-icon": EyeIcon,
  "glasses-icon": GlassesIcon,
  contact: Contact,
  contact2: Contact2,
  "user-icon": UserIcon,
  "user-plus": UserPlus,
  "user-minus": UserMinus,
  "user-x": UserX,
  "user-check": UserCheck,
  users: Users,
  "users-plus": UsersPlus,
  "users-minus": UsersMinus,
  "users-x": UsersX,
  "users-round": UsersRound,
  "user-circle": UserCircle,
  "user-cog": UserCog,
  "user-cog-2": UserCog2,
  "user-round": UserRound,
  baby: Baby,
  accessibility: Accessibility,
  "accessibility-icon": AccessibilityIcon,
  armchair: Armchair,
  bath: Bath,
  bed: Bed,
  "bed-double": BedDouble,
  "bed-single": BedSingle,
  sofa: Sofa,
  lamp: Lamp,
  "lamp-desk": LampDesk,
  "lamp-floor": LampFloor,
  "lamp-wall": LampWall,
  "lightbulb-icon": LightbulbIcon,
  flashlight: Flashlight,
  "candlestick-chart": CandlestickChart,
  "flame-kindling": FlameKindling,
  "fire-extinguisher": FireExtinguisher,
  hydrant: Hydrant,
  siren: Siren,
  "alert-octagon": AlertOctagon,
  "alert-circle": AlertCircle,
  "alert-triangle-icon": AlertTriangleIcon,
  "megaphone-icon": MegaphoneIcon,
  "bell-icon": BellIcon,
  "bell-plus": BellPlus,
  "bell-minus": BellMinus,
  "bell-off": BellOff,
  "bell-ring-icon": BellRingIcon,
  "bell-dot": BellDot,
  "package-icon": PackageIcon,
  "package-2": Package2,
  "package-check": PackageCheck,
  "package-x": PackageX,
  "package-search": PackageSearch,
  "package-open": PackageOpen,
  container: Container,
  "shipping-container": ShippingContainer,
  "truck-icon": TruckIcon,
  "plane-icon": PlaneIcon,
  "plane-takeoff": PlaneTakeoff,
  "plane-landing": PlaneLanding,
  train: Train,
  "train-front": TrainFront,
  bus: Bus,
  "car-icon": CarIcon,
  "car-front": CarFront,
  "car-taxi-front": CarTaxiFront,
  bike: Bike,
  footprints: Footprints,
  "map-pinned": MapPinned,
  "map-icon": MapIcon,
  "globe-2": Globe2,
  "globe-icon": GlobeIcon,
  earth: Earth,
  languages: Languages,
  "book-icon": BookIcon,
  "book-copy": BookCopy,
  "book-down": BookDown,
  "book-key": BookKey,
  "book-lock": BookLock,
  "book-up": BookUp,
  "book-x": BookX,
  "bookmark-icon": BookmarkIcon,
  "bookmark-plus": BookmarkPlus,
  "bookmark-minus": BookmarkMinus,
  "bookmark-x": BookmarkX,
  "bookmark-check": BookmarkCheck,
  "library-icon": LibraryIcon,
  "graduation-cap-icon": GraduationCapIcon,
  "award-icon": AwardIcon,
  "medal-icon": MedalIcon,
  "trophy-icon": TrophyIcon,
  "crown-icon": CrownIcon,
};

interface IconPickerProps {
  value: string;
  onChange: (icon: string) => void;
  color?: string;
}

export function IconPicker({ value, onChange, color = "#6366f1" }: IconPickerProps) {
  const [open, setOpen] = useState(false);
  const [search, setSearch] = useState("");

  // Check if current value is an emoji
  const isEmoji = EMOJI_ICONS.includes(value);
  const displayValue = isEmoji ? value : value;

  // Get Lucide icon component
  const getLucideIcon = (name: string) => {
    const Icon = LUCIDE_ICONS[name];
    return Icon ? <Icon className="h-5 w-5" /> : null;
  };

  const filteredEmojis = EMOJI_ICONS.filter((emoji) =>
    search ? emoji.includes(search) || getEmojiName(emoji).toLowerCase().includes(search.toLowerCase()) : true
  );

  const filteredLucide = Object.keys(LUCIDE_ICONS).filter((name) =>
    search ? name.toLowerCase().includes(search.toLowerCase()) : true
  );

  // Helper to get a readable name for emoji
  function getEmojiName(emoji: string): string {
    const names: Record<string, string> = {
      "💼": "Briefcase", "📚": "Books", "💪": "Fitness", "👤": "Person",
      "💻": "Computer", "☕": "Coffee", "🎵": "Music", "🎬": "Movie",
      "🎮": "Game", "🛍️": "Shopping", "🏠": "Home", "🚗": "Car",
      "✈️": "Plane", "❤️": "Love", "⭐": "Star", "☀️": "Sun",
      "🌙": "Moon", "☁️": "Cloud", "⚡": "Lightning", "🔥": "Fire",
      "🎯": "Target", "🏆": "Trophy", "🥇": "Gold", "🏅": "Medal",
      "💡": "Idea", "✏️": "Edit", "🎨": "Art", "📷": "Camera",
      "🎤": "Mic", "🎧": "Headphones", "📺": "TV", "📱": "Phone",
    };
    return names[emoji] || "Emoji";
  }

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <button
          type="button"
          className="flex items-center gap-2 rounded-lg border border-border bg-background px-3 py-2 hover:bg-accent transition-colors"
        >
          <div
            className="flex h-8 w-8 items-center justify-center rounded-full text-white font-medium text-lg"
            style={{ backgroundColor: color }}
          >
            {isEmoji ? value : getLucideIcon(value)}
          </div>
          <span className="text-sm text-muted-foreground capitalize">
            {isEmoji ? getEmojiName(value) : value.replace(/-/g, " ")}
          </span>
        </button>
      </DialogTrigger>
      <DialogContent className="max-w-md max-h-[80vh] overflow-hidden">
        <DialogHeader>
          <DialogTitle>Choose Icon</DialogTitle>
        </DialogHeader>
        <div className="space-y-4">
          <Input
            placeholder="Search icons..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
          <Tabs defaultValue="emoji" className="w-full">
            <TabsList className="grid w-full grid-cols-2">
              <TabsTrigger value="emoji">Emoji</TabsTrigger>
              <TabsTrigger value="lucide">Icons</TabsTrigger>
            </TabsList>
            <TabsContent value="emoji" className="mt-4">
              <div className="grid grid-cols-8 gap-2 max-h-[300px] overflow-y-auto p-1">
                {filteredEmojis.map((emoji) => (
                  <button
                    key={emoji}
                    type="button"
                    onClick={() => {
                      onChange(emoji);
                      setOpen(false);
                    }}
                    className={cn(
                      "flex h-10 w-10 items-center justify-center rounded-lg text-xl hover:bg-accent transition-colors",
                      value === emoji && "bg-primary/10 ring-2 ring-primary"
                    )}
                    title={getEmojiName(emoji)}
                  >
                    {emoji}
                  </button>
                ))}
              </div>
            </TabsContent>
            <TabsContent value="lucide" className="mt-4">
              <div className="grid grid-cols-6 gap-2 max-h-[300px] overflow-y-auto p-1">
                {filteredLucide.map((name) => {
                  const Icon = LUCIDE_ICONS[name];
                  if (!Icon) return null;
                  return (
                    <button
                      key={name}
                      type="button"
                      onClick={() => {
                        onChange(name);
                        setOpen(false);
                      }}
                      className={cn(
                        "flex h-10 w-10 items-center justify-center rounded-lg hover:bg-accent transition-colors",
                        value === name && "bg-primary/10 ring-2 ring-primary"
                      )}
                      title={name.replace(/-/g, " ")}
                    >
                      <Icon className="h-5 w-5" />
                    </button>
                  );
                })}
              </div>
            </TabsContent>
          </Tabs>
        </div>
      </DialogContent>
    </Dialog>
  );
}

// Helper to render icon in category card
export function CategoryIcon({
  icon,
  color,
  size = "md",
}: {
  icon: string;
  color: string;
  size?: "sm" | "md" | "lg";
}) {
  const sizeClasses = {
    sm: "h-8 w-8 text-sm",
    md: "h-10 w-10 text-base",
    lg: "h-12 w-12 text-lg",
  };

  // Check if it's an emoji
  const isEmoji = EMOJI_ICONS.includes(icon);

  if (isEmoji) {
    return (
      <div
        className={`flex ${sizeClasses[size]} items-center justify-center rounded-full text-white font-medium`}
        style={{ backgroundColor: color }}
      >
        {icon}
      </div>
    );
  }

  // Lucide icon
  const IconComponent = LUCIDE_ICONS[icon];
  if (IconComponent) {
    return (
      <div
        className={`flex ${sizeClasses[size]} items-center justify-center rounded-full text-white`}
        style={{ backgroundColor: color }}
      >
        <IconComponent className={size === "lg" ? "h-6 w-6" : size === "sm" ? "h-4 w-4" : "h-5 w-5"} />
      </div>
    );
  }

  // Fallback to first letter
  return (
    <div
      className={`flex ${sizeClasses[size]} items-center justify-center rounded-full text-white font-medium`}
      style={{ backgroundColor: color }}
    >
      {icon[0]?.toUpperCase() || "?"}
    </div>
  );
}

// Helper to get icon display name
export function getIconName(icon: string): string {
  const names: Record<string, string> = {
    "💼": "Briefcase", "📚": "Books", "💪": "Fitness", "👤": "Person",
    "💻": "Computer", "☕": "Coffee", "🎵": "Music", "🎬": "Movie",
    "🎮": "Game", "🛍️": "Shopping", "🏠": "Home", "🚗": "Car",
    "✈️": "Plane", "❤️": "Love", "⭐": "Star", "☀️": "Sun",
    "🌙": "Moon", "☁️": "Cloud", "⚡": "Lightning", "🔥": "Fire",
    "🎯": "Target", "🏆": "Trophy", "🥇": "Gold", "🏅": "Medal",
    "💡": "Idea", "✏️": "Edit", "🎨": "Art", "📷": "Camera",
    "🎤": "Mic", "🎧": "Headphones", "📺": "TV", "📱": "Phone",
  };

  if (names[icon]) return names[icon];
  if (EMOJI_ICONS.includes(icon)) return "Emoji";
  return icon.replace(/-/g, " ");
}
